SELECT ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
WHERE NOT SEX_UPON_INTAKE = SEX_UPON_OUTCOME
ORDER BY ANIMAL_ID, O.ANIMAL_TYPE, O.NAME

-- WHERE SEX_UPON_INTAKE != SEX_UPON_OUTCOME