-- 주문량이 많은 아이스크림들 조회하기

SELECT FLAVOR
FROM
(
    SELECT J.FLAVOR FLAVOR, 
        COUNT(1) CNT, 
        SUM(J.TOTAL_ORDER) + H.TOTAL_ORDER TOTAL_ORDER
    FROM FIRST_HALF H
    JOIN JULY J USING (FLAVOR)
    GROUP BY FLAVOR
    ORDER BY 3 DESC
) A
LIMIT 3

-- 어떤 컬럼을 키값으로 해야하는지 헷갈렸다.

SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
    
        UNION ALL
    
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) AS CombinedFlavors
    GROUP BY FLAVOR
) AS FinalFlavors
ORDER BY TOTAL_ORDER DESC
LIMIT 3;