-- 저자 별 카테고리 별 매출액 집계하기

SELECT AUTHOR_ID, 
    AUTHOR_NAME, 
    CATEGORY, 
    SUM(TOTAL_SALES) TOTAL_SALES
FROM
(
    SELECT 
    A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    B.PRICE * S.SALES TOTAL_SALES
    FROM BOOK B
    INNER JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID
    INNER JOIN BOOK_SALES S ON B.BOOK_ID=S.BOOK_ID
    WHERE YEAR(S.SALES_DATE)=2022 AND MONTH(S.SALES_DATE)=1
) A
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC