SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_PRICE
FROM USED_GOODS_BOARD
JOIN USED_GOODS_USER ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
GROUP BY NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_PRICE